const customRankings = [
    { name: "Iron Gwazi", park: "Busch Gardens Tampa" },
    { name: "Wildcat's Revenge", park: "Hersheypark" },
    { name: "VelociCoaster", park: "Universal Studios Islands of Adventure" },
    { name: "Steel Vengeance", park: "Cedar Point" },
    { name: "Skyrush", park: "Hersheypark" },
    { name: "Millennium Force", park: "Cedar Point" },
    { name: "Outlaw Run", park: "Silver Dollar City" },
    { name: "Iron Rattler", park: "Six Flags Fiesta Texas" },
    { name: "El Toro", park: "Six Flags Great Adventure" },
    { name: "X2", park: "Six Flags Magic Mountain" },
    { name: "RailBlazer", park: "California's Great America" },
    { name: "Wonder Woman Golden Lasso Coaster", park: "Six Flags Fiesta Texas" },
    { name: "Storm Runner", park: "Hersheypark" },
    { name: "Magnum XL-200", park: "Cedar Point" },
    { name: "Mako", park: "SeaWorld Orlando" },
    { name: "Top Thrill 2", park: "Cedar Point" },
    { name: "Kingda Ka", park: "Six Flags Great Adventure" },
    { name: "Twisted Colossus", park: "Six Flags Magic Mountain" },
    { name: "Gold Striker", park: "California's Great America" },
    { name: "Beast", park: "Kings Island" },
    { name: "Cannibal", park: "Lagoon" },
    { name: "Pipeline the Surf Coaster", park: "SeaWorld Orlando" },
    { name: "Diamondback", park: "Kings Island" },
    { name: "Wonder Woman Flight of Courage", park: "Six Flags Magic Mountain" },
    { name: "Jersey Devil Coaster", park: "Six Flags Great Adventure" },
    { name: "Nitro", park: "Six Flags Great Adventure" },
    { name: "Candymonium", park: "Hersheypark" },
    { name: "Poltergeist", park: "Six Flags Fiesta Texas" },
    { name: "Mr. Freeze", park: "Six Flags Over Texas" },
    { name: "Xcelerator", park: "Knott's Berry Farm" },
    { name: "GhostRider", park: "Knott's Berry Farm" },
    { name: "Incredible Hulk", park: "Universal Studios Islands of Adventure" },
    { name: "Montu", park: "Busch Gardens Tampa" },
    { name: "New Texas Giant", park: "Six Flags Over Texas" },
    { name: "Viper", park: "Six Flags Magic Mountain" },
    { name: "Vortex", park: "Kings Island" },
    { name: "Steel Eel", park: "SeaWorld San Antonio" },
    { name: "Goliath", park: "Six Flags Fiesta Texas" },
    { name: "Great White", park: "SeaWorld San Antonio" },
    { name: "Big Apple Coaster", park: "New York, New York Hotel & Casino" },
    { name: "Roller Coaster", park: "Lagoon" },
    { name: "Colossus the Fire Dragon", park: "Lagoon" },
    { name: "Jet Star 2", park: "Lagoon" },
    { name: "Wild Mouse", park: "Lagoon" },
    { name: "Wicked", park: "Lagoon" },
    { name: "Spider", park: "Lagoon" },
    { name: "Primordial", park: "Lagoon" },
    { name: "Giant Dipper", park: "Santa Cruz Beach Boardwalk" },
    { name: "Giant Dipper", park: "Belmont Park" },
    { name: "Demon", park: "California's Great America" },
    { name: "Grizzly", park: "California's Great America" },
    { name: "Woodstock Express", park: "California's Great America" },
    { name: "Patriot", park: "California's Great America" },
    { name: "Flight Deck", park: "California's Great America" },
    { name: "Lucy's Crabbie Cabbies", park: "California's Great America" },
    { name: "Psycho Mouse", park: "California's Great America" },
    { name: "Invertigo", park: "California's Great America" },
    { name: "Incredicoaster", park: "Disney California Adventure Park" },
    { name: "Goofy's Sky School", park: "Disney California Adventure Park" },
    { name: "Matterhorn Bobsleds", park: "Disneyland" },
    { name: "Space Mountain", park: "Disneyland" },
    { name: "Big Thunder Mountain Railroad", park: "Disneyland" },
    { name: "Chip & Dale’s Gadget Coaster", park: "Disneyland" },
    { name: "Quicksilver Express", park: "Gilroy Gardens Family Theme Park" },
    { name: "Timber Twister", park: "Gilroy Gardens Family Theme Park"},
    { name: "Jaguar!", park: "Knott's Berry Farm" },
    { name: "HangTime", park: "Knott's Berry Farm" },
    { name: "Montezooma's Revenge", park: "Knott's Berry Farm" },
    { name: "Boomerang", park: "Knott's Berry Farm" },
    { name: "Boomerang", park: "Six Flags Discovery Kingdom" },
    { name: "Batman The Ride", park: "Six Flags Great Adventure" },
    { name: "Superman: Escape from Krypton", park: "Six Flags Magic Mountain" },
    { name: "Full Throttle", park: "Six Flags Magic Mountain" },
    { name: "Scream!", park: "Six Flags Magic Mountain" },
    { name: "Tatsu", park: "Six Flags Magic Mountain" },
    { name: "Apocalypse the Ride", park: "Six Flags Magic Mountain" },
    { name: "Roar", park: "Six Flags Discovery Kingdom" },
    { name: "Medusa", park: "Six Flags Discovery Kingdom" },
    { name: "Medusa", park: "Six Flags Great Adventure" },
    { name: "Superman Ultimate Flight", park: "Six Flags Discovery Kingdom" },
    { name: "Shredder", park: "Nickelodeon Universe" },
    { name: "Kraken", park: "SeaWorld Orlando" },
    { name: "Hagrid's Magical Creatures Motorbike Adventure", park: "Universal Studios Islands of Adventure" },
    { name: "Time Traveler", park: "Silver Dollar City" },
    { name: "Flight of Fear", park: "Kings Island" },
    { name: "Big Apple Coaster", park: "New York-New York Hotel & Casino" },
    { name: "Scorpion", park: "Busch Gardens Tampa" },
    { name: "SandSerpent", park: "Busch Gardens Tampa" },
    { name: "Journey to Atlantis", park: "SeaWorld Orlando" },
    { name: "Journey to Atlantis", park: "SeaWorld San Diego" },
    { name: "Journey to Atlantis", park: "SeaWorld San Antonio" },
    { name: "Manta", park: "SeaWorld Orlando" },
    { name: "Manta", park: "SeaWorld San Diego" },
    { name: "Ice Breaker", park: "SeaWorld Orlando" },
    { name: "Revenge of the Mummy", park: "Universal Studios Florida" },
    { name: "Revenge of the Mummy the Ride", park: "Universal Studios Hollywood" },
    { name: "Hollywood Rip, Ride, Rockit", park: "Universal Studios Florida" },
    { name: "Harry Potter and the Escape from Gringotts", park: "Universal Studios Florida" },
    { name: "Flight of the Hippogriff", park: "Universal Studios Islands of Adventure" },
    { name: "Expedition Everest", park: "Walt Disney World - Disney's Animal Kingdom" },
    { name: "Primeval Whirl", park: "Walt Disney World - Disney's Animal Kingdom" },
    { name: "Rock 'n' Roller Coaster", park: "Walt Disney World - Disney's Hollywood Studios" },
    { name: "Thunderation", park: "Silver Dollar City" },
    { name: "Wildfire", park: "Silver Dollar City" },
    { name: "Powder Keg: A Blast in the Wilderness", park: "Silver Dollar City" },
    { name: "Fire In The Hole", park: "Silver Dollar City" },
    { name: "Shredder", park: "Nickelodeon Universe Theme Park" },
    { name: "Nickelodeon Slime Streak", park: "Nickelodeon Universe Theme Park" },
    { name: "Sandy’s Blasting Bronco", park: "Nickelodeon Universe Theme Park" },
    { name: "TMNT Shellraiser", park: "Nickelodeon Universe Theme Park" },
    { name: "Joker", park: "Six Flags Great Adventure" },
    { name: "Joker", park: "Six Flags Over Texas" },
    { name: "Joker", park: "Six Flags Discovery Kingdom" },
    { name: "Flash: Vertical Velocity", park: "Six Flags Discovery Kingdom" },
    { name: "Pandemonium", park: "Six Flags Discovery Kingdom" },
    { name: "Dark Knight", park: "Six Flags Great Adventure" },
    { name: "Skull Mountain", park: "Six Flags Great Adventure" },
    { name: "Runaway Mine Train", park: "Six Flags Great Adventure" },
    { name: "Iron Dragon", park: "Cedar Point" },
    { name: "Cedar Creek Mine Ride", park: "Cedar Point" },
    { name: "Maverick", park: "Cedar Point" },
    { name: "GateKeeper", park: "Cedar Point" },
    { name: "Valravn", park: "Cedar Point" },
    { name: "Raptor", park: "Cedar Point" },
    { name: "Rougarou", park: "Cedar Point" },
    { name: "Blue Streak", park: "Cedar Point" },
    { name: "Corkscrew", park: "Cedar Point" },
    { name: "Gemini", park: "Cedar Point" },
    { name: "Wicked Twister", park: "Cedar Point" },
    { name: "Racer", park: "Kings Island" },
    { name: "Adventure Express", park: "Kings Island" },
    { name: "Bat", park: "Kings Island" },
    { name: "Invertigo", park: "Kings Island" },
    { name: "Banshee", park: "Kings Island" },
    { name: "Mystic Timbers", park: "Kings Island" },
    { name: "Woodstock’s Air Rail", park: "Kings Island" },
    { name: "Backlot Stunt Coaster", park: "Kings Island" },
    { name: "Firehawk", park: "Kings Island" },
    { name: "Comet", park: "Hersheypark" },
    { name: "Sooperdooperlooper", park: "Hersheypark" },
    { name: "Great Bear", park: "Hersheypark" },
    { name: "Lightning Racer", park: "Hersheypark" },
    { name: "Fahrenheit", park: "Hersheypark" },
    { name: "Laff Trakk", park: "Hersheypark" },
    { name: "Wave Breaker: The Rescue Coaster", park: "SeaWorld San Antonio" },
    { name: "Texas Stingray", park: "SeaWorld San Antonio" },
    { name: "Superman Krypton Coaster", park: "Six Flags Fiesta Texas" },
    { name: "Batman The Ride", park: "Six Flags Over Texas" },
    { name: "Batman The Ride", park: "Six Flags Discovery Kingdom" },
    { name: "Batman The Ride", park: "Six Flags Fiesta Texas" },
    { name: "Dr. Diabolical's Cliffhanger", park: "Six Flags Fiesta Texas" },
    { name: "Pandemonium", park: "Six Flags Over Texas" },
    { name: "Aquaman: Power Wave", park: "Six Flags Over Texas" },
    { name: "Shock Wave", park: "Six Flags Over Texas" },
    { name: "Judge Roy Scream", park: "Six Flags Over Texas" },
    { name: "Runaway Mine Train", park: "Six Flags Over Texas" },
    { name: "Runaway Mountain", park: "Six Flags Over Texas" },
    { name: "Mini Mine Train", park: "Six Flags Over Texas" },
    { name: "Titan", park: "Six Flags Over Texas" },
    { name: "La Vibora", park: "Six Flags Over Texas" },
    { name: "Quicksilver Express", park: "Gilroy Gardens" },
    { name: "Timber Twister", park: "Northwoods Adventure" },
    { name: "Pacific Fruit Express", park: "Happy Hollow Park and Zoo" },
    { name: "Silver Bullet", park: "Knott's Berry Farm" },
    { name: "Sierra Sidewinder", park: "Knott's Berry Farm" },
    { name: "Pony Express", park: "Knott's Berry Farm" },
    { name: "Coast Rider", park: "Knott's Berry Farm" },
    { name: "Timberline Twister", park: "Knott's Berry Farm" },
    { name: "Dragon", park: "Legoland California" },
    { name: "Technic Coaster", park: "Legoland California" },
    { name: "Coastersaurus", park: "Legoland California" },
    { name: "Tiger Trek", park: "Oakland Zoo" },
    { name: "Santa Monica West Coaster", park: "Pacific Park" },
    { name: "Sea Serpent", park: "Santa Cruz Beach Boardwalk" },
    { name: "Undertow", park: "Santa Cruz Beach Boardwalk" },
    { name: "Hurricane", park: "Santa Cruz Beach Boardwalk" },
    { name: "Electric Eel", park: "SeaWorld San Diego" },
    { name: "Emperor", park: "SeaWorld San Diego" },
    { name: "Arctic Rescue", park: "SeaWorld San Diego" },
    { name: "Tidal Twister", park: "SeaWorld San Diego" },
    { name: "Roadrunner Express", park: "Six Flags Magic Mountain" },
    { name: "Roadrunner Express", park: "Six Flags Discovery Kingdom" },
    { name: "Cobra", park: "Six Flags Discovery Kingdom" },
    { name: "Kong", park: "Six Flags Discovery Kingdom" },
    { name: "Harley Quinn Crazy Coaster", park: "Six Flags Discovery Kingdom" },
    { name: "Ninja", park: "Six Flags Magic Mountain" },
    { name: "New Revolution", park: "Six Flags Magic Mountain" },
    { name: "Batman The Ride", park: "Six Flags Magic Mountain" },
    { name: "Green Lantern: First Flight", park: "Six Flags Magic Mountain" },
    { name: "Desert Storm", park: "Castles n' Coasters" },
    { name: "Patriot", park: "Castles n' Coasters" },
    { name: "Alpine Coaster", park: "Park City Mountain Resort" },
    { name: "Kumba", park: "Busch Gardens Tampa" },
    { name: "SheiKra", park: "Busch Gardens Tampa" },
    { name: "Air Grover", park: "Busch Gardens Tampa" },
    { name: "Cheetah Hunt", park: "Busch Gardens Tampa" },
    { name: "Cobra's Curse", park: "Busch Gardens Tampa" },
    { name: "Tigris", park: "Busch Gardens Tampa" },
    { name: "Gold Rusher", park: "Six Flags Magic Mountain" },
    { name: "Riddler's Revenge", park: "Six Flags Magic Mountain" },
    { name: "Canyon Blaster", park: "Six Flags Magic Mountain" },
    { name: "Goliath", park: "Six Flags Magic Mountain" },
    { name: "Road Runner Express", park: "Six Flags Magic Mountain" },
    { name: "Speedy Gonzales Hot Rod Racers", park: "Six Flags Magic Mountain" },
    { name: "West Coast Racers", park: "Six Flags Magic Mountain" },
    { name: "Colossus", park: "Six Flags Magic Mountain" },
    { name: "Alpine Coaster", park: "Glenwood Caverns Adventure Park" },
  ];
  
  export default customRankings;
  