const customRankings = [
    { name: "Iron Gwazi", park: "Busch Gardens Tampa" },
    { name: "Wildcat's Revenge", park: "Hersheypark" },
    { name: "VelociCoaster", park: "Universal's Islands of Adventure" },
    { name: "Steel Vengeance", park: "Cedar Point" },
    { name: "Skyrush", park: "Hersheypark" },
    { name: "Millennium Force", park: "Cedar Point" },
    { name: "Outlaw Run", park: "Silver Dollar City" },
    { name: "Iron Rattler", park: "Six Flags Fiesta Texas" },
    { name: "El Toro", park: "Six Flags Great Adventure" },
    { name: "X2", park: "Six Flags Magic Mountain" },
    { name: "RailBlazer", park: "California's Great America" },
    { name: "Wonder Woman Golden Lasso Coaster", park: "Six Flags Fiesta Texas" },
    { name: "Storm Runner", park: "Hersheypark" },
    { name: "Magnum XL-200", park: "Cedar Point" },
    { name: "Mako", park: "SeaWorld Orlando" },
    { name: "Top Thrill 2", park: "Cedar Point" },
    { name: "Kingda Ka", park: "Six Flags Great Adventure" },
    { name: "Twisted Colossus", park: "Six Flags Magic Mountain" },
    { name: "Gold Striker", park: "California's Great America" },
    { name: "Cannibal", park: "Lagoon" },
    { name: "Pipeline the Surf Coaster", park: "SeaWorld Orlando" },
    { name: "Diamondback", park: "Kings Island" },
    { name: "Wonder Woman Flight of Courage", park: "Six Flags Great Adventure" },
    { name: "Jersey Devil Coaster", park: "Six Flags Great Adventure" },
    { name: "Nitro", park: "Six Flags Great Adventure" },
    { name: "Poltergeist", park: "Six Flags Fiesta Texas" },
    { name: "Mr. Freeze", park: "Six Flags Over Texas"},
    { name: "Xcelerator", park: "Knott's Berry Farm" },
    { name: "GhostRider", park: "Knott's Berry Farm" },
    { name: "Incredible Hulk", park: "Universal's Islands of Adventure" },
    { name: "Montu", park: "Busch Gardens Tampa" },
    { name: "New Texas Giant", park: "Six Flags Over Texas" },
    { name: "Viper", park: "Six Flags Magic Mountain" },
    { name: "Vortex", park: "Kings Island" },
  ];
  export default customRankings;

  /*  { name: " ", park: " " }, */